## Livro

Bibliotecas - Pag 15 e 16

Cookiecutter (Pag 21): https://github.com/drivendata/cookiecutter-data-science

## **Bibliotecas (Import)**


In [11]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

## **Coleta de dados**


In [12]:
df = pd.read_csv("titanic.csv").drop(1309)
df

pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton   
1        1.0       1.0                   Allison, Master. Hudson Trevor   
2        1.0       0.0                     Allison, Miss. Helen Loraine   
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton   
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304     3.0       0.0                             Zabour, Miss. Hileni   
1305     3.0       0.0                            Zabour, Miss. Thamine   
1306     3.0       0.0                        Zakarian, Mr. Mapriededer   
1307     3.0       0.0                              Zakarian, Mr. Ortin   
1308     3.0       0.0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000    0.0    0.0   24160  211.3375       B5        S    2   
1       male   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11   
2     female   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000    1.0    0.0    2665   14.4542      NaN        C  NaN   
1305  female      NaN    1.0    0.0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000    0.0    0.0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000    0.0    0.0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000    0.0    0.0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [13]:
X2  = pd.DataFrame(
    {
    "a" : range(5),
    "b" : [-100, -50, 0, 200, 1000]
     }
)
X2

a     b
0  0  -100
1  1   -50
2  2     0
3  3   200
4  4  1000

## **Padronize os dados (StandardScaler)**

In [14]:
X_std = (X2 - X2.mean())/X2.std()
X_std

a         b
0 -1.264911 -0.679720
1 -0.632456 -0.570088
2  0.000000 -0.460455
3  0.632456 -0.021926
4  1.264911  1.732190

## **Padronize os dados**

In [15]:
from sklearn import preprocessing

std = preprocessing.StandardScaler()
_ = std.fit_transform(X2)
pd.DataFrame(_, columns=['a','b'])

a         b
0 -1.414214 -0.759950
1 -0.707107 -0.637377
2  0.000000 -0.514805
3  0.707107 -0.024515
4  1.414214  1.936647

Dimensionamento relativo por recurso dos dados para atingir média zero e variação de unidade.

In [16]:
std.scale_

array([  1.41421356, 407.92156109])

O valor médio para cada recurso no conjunto de treinamento.

In [17]:
std.mean_

array([  2., 210.])

A variação para cada recurso no conjunto de treinamento.

In [18]:
std.var_

array([2.000e+00, 1.664e+05])

## **Escale para um intervalo (MinMaxScaler)**


In [19]:
X_mms = (X2 - X2.min())/(X2.max() - X2.min())
X_mms

a         b
0  0.00  0.000000
1  0.25  0.045455
2  0.50  0.090909
3  0.75  0.272727
4  1.00  1.000000

In [20]:
from sklearn import preprocessing

mms = preprocessing.MinMaxScaler()
_ = mms.fit_transform(X2)
pd.DataFrame(_, columns=['a','b'])

a         b
0  0.00  0.000000
1  0.25  0.045455
2  0.50  0.090909
3  0.75  0.272727
4  1.00  1.000000

## **Variáveis Dummy**


In [21]:
X_cat  = pd.DataFrame(
    {
    "name" : ["George", "Paul"],
    "inst" : ["Bass", "Guitar"]
     }
)
X_cat

name    inst
0  George    Bass
1    Paul  Guitar

In [22]:
pd.get_dummies(X_cat, drop_first=True) #eliminar uma coluna das colunas dummies (combinação linear)

name_Paul  inst_Guitar
0          0            0
1          1            1

## **Codificador de Rótulos (Label enconding)**


LabelEnconder()

In [23]:
X_cat

name    inst
0  George    Bass
1    Paul  Guitar

In [24]:
lab = preprocessing.LabelEncoder()
print(lab.fit_transform(X_cat.name)) #LabelEncoding (coluna por vez)
(lab.inverse_transform([0, 1])) #Reverter

[0 1]


array(['George', 'Paul'], dtype=object)

Pandas puro

In [25]:
X_cat.name.astype(
    "category"
).cat.as_ordered().cat.codes

0    0
1    1
dtype: int8

## **Codificador de Frequência**


In [26]:
mapping = X_cat.name.value_counts()
X_cat.name.map(mapping)

0    1
1    1
Name: name, dtype: int64

## **Extraindo categoria a partir de strings**


Você pode criar variaveis dummies ou combinar colunas com contadores baixos em outras categorias (ou descarta-los)

In [27]:
from collections import Counter
c = Counter()
def triples(val):
  for i in range(len(val)):
    c[val[i: i + 3]] +=1
  
df.name.apply(triples)
c.most_common(10)

[(', M', 1282),
 (' Mr', 954),
 ('r. ', 830),
 ('Mr.', 757),
 ('s. ', 460),
 ('n, ', 320),
 (' Mi', 283),
 ('iss', 261),
 ('ss.', 261),
 ('Mis', 260)]

In [28]:
df.name.str.extract(
    "([A-Za-z]+)\.", expand=False
).value_counts()

Mr          757
Miss        260
Mrs         197
Master       61
Rev           8
Dr            8
Col           4
Mlle          2
Ms            2
Major         2
Capt          1
Sir           1
Dona          1
Jonkheer      1
Countess      1
Don           1
Mme           1
Lady          1
Name: name, dtype: int64

## **Outras codificações de categorias (Category_encoders)**


In [33]:
#!pip install category_encoders

In [34]:
X_cat

name    inst
0  George    Bass
1    Paul  Guitar

In [35]:
import category_encoders as ce
he = ce.HashingEncoder(verbose=1)
he.fit_transform(X_cat)

col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0      0      0      0      1      0      1      0      0
1      0      2      0      0      0      0      0      0

OrdinalEncoder - Normalizar usando ordem

In [ ]:
size_df = pd.DataFrame(
    {
        "name" : ['Fred', 'John', 'Matt'],
        "size" : ['small', 'med', 'xxl']

    }
)

In [36]:
ore = ce.OrdinalEncoder(
    mapping=[
        {
            "col" : "size",
            "mapping" : {
                "small" : 1,
                "med" : 2,
                "lg" : 3       
            }
        }
    ]
)

ore.fit_transform(size_df)

name  size
0  Fred   1.0
1  John   2.0
2  Matt  -1.0

In [56]:
#Mais de uma coluna
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['small','med','xxl']])
oe.fit_transform(size_df[['size']])

array([[0.],
       [1.],
       [2.]])

Por exemplo, para converter a coluna de sobrevivência do Titanic em uma mistura de probabilidade posterior do alvo e probabilidade anterior dada a informação do título (categorial)

In [37]:
def get_title(df):
     return df.name.str.extract(
         "([A-Za-z]+)\.", expand=False
     )
te = ce.TargetEncoder(cols="Title")
te.fit_transform(
    df.assign(Title=get_title), df.survived
)["Title"].head()

/usr/local/lib/python3.8/dist-packages/category_encoders/target_encoder.py:122: FutureWarning: Default parameter min_samples_leaf will change in version 2.6.See https://github.com/scikit-learn-contrib/category_encoders/issues/327
  warnings.warn("Default parameter min_samples_leaf will change in version 2.6."
/usr/local/lib/python3.8/dist-packages/category_encoders/target_encoder.py:127: FutureWarning: Default parameter smoothing will change in version 2.6.See https://github.com/scikit-learn-contrib/category_encoders/issues/327
  warnings.warn("Default parameter smoothing will change in version 2.6."


0    0.676923
1    0.508197
2    0.676923
3    0.162483
4    0.786802
Name: Title, dtype: float64

## **Engenharia de dados para datas**


In [38]:
#!pip install torchvision fastai==0.6

add_datepart altera o Dataframe

In [40]:
# from fastai.tabular.transform import (
#     add_datepart,
# )
# dates = pd.DataFrame(
#     {
#         "A": pd.to_datetime(
#             ["9/17/2001", "Jan 1, 2002"]
#         )
#     }
# )

# add_datepart(dates, "A")
# dates.T

## **Adição do atributo col_na**


In [41]:
data = pd.DataFrame({"A": [0, None, 5, 100]})
data["A_na"] = data.A.isnull()
data["A"] = data.A.fillna(data.A.median())
data

A   A_na
0    0.0  False
1    5.0   True
2    5.0  False
3  100.0  False

## **Engenharia de dados manual**


idade máxima por cabine, idade média por cabine, etc.

In [42]:
agg = (
    df.groupby("cabin")
    .agg("min,max,mean,sum".split(","))
    .reset_index()
)
agg.columns = [
    "_".join(c).strip("_")
    for c in agg.columns.values
]
agg_df = df.merge(agg, on="cabin")

## **Make Column Transformer**
Mais de uma transformação de uma vez. Ela é útil quando há necessidade de realizar diferentes tipos de pré-processamento em diferentes colunas do conjunto de dados, como normalização em uma coluna e encoding em outra.

In [43]:
teste = pd.read_csv('http://bit.ly/kaggletrain', nrows=6)
cols = ['Fare', 'Embarked', 'Sex', 'Age']
teste_X = teste[cols]
teste_X

Fare Embarked     Sex   Age
0   7.2500        S    male  22.0
1  71.2833        C  female  38.0
2   7.9250        S  female  26.0
3  53.1000        S  female  35.0
4   8.0500        S    male  35.0
5   8.4583        Q    male   NaN

In [44]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

ohe = OneHotEncoder()
imp = SimpleImputer()

In [45]:
from sklearn.compose import make_column_transformer

ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),  # apply OneHotEncoder to Embarked and Sex
    (imp, ['Age']),              # apply SimpleImputer to Age
    remainder='passthrough')     # include remaining column (Fare) in the output

ct.fit_transform(teste_X)
pd.DataFrame(_)

0         1
0  0.00  0.000000
1  0.25  0.045455
2  0.50  0.090909
3  0.75  0.272727
4  1.00  1.000000